#ifndef TLSSERVERDEFINES_H_INCLUDED
#define TLSSERVERDEFINES_H_INCLUDED

namespace HS_Networking
{
enum: int
{
    NETWORKING_START_OK                              = 0,
    NETWORKING_ERROR_START_WRONG_PORT                = 10,
    NETWORKING_ERROR_START_SET_CONTEXT               = 20,
    NETWORKING_ERROR_START_WRONG_CA_PATH             = 30,
    NETWORKING_ERROR_START_WRONG_CERT_PATH           = 31,
    NETWORKING_ERROR_START_WRONG_KEY_PATH            = 32,
    NETWORKING_ERROR_START_WRONG_KEY                 = 33,
    NETWORKING_ERROR_START_CREATE_SOCKET             = 40,
    NETWORKING_ERROR_START_SET_SOCKET_OPT            = 41,
    NETWORKING_ERROR_START_BIND_PORT                 = 42,
    NETWORKING_ERROR_START_LISTENER                  = 43
};

enum: char
{
    NETWORKING_CHAR_TRANSFER_START  = '\x02',
    NETWORKING_CHAR_TRANSFER_END    = '\x03'
};
}

#endif // TLSSERVERDEFINES_H_INCLUDED
